from ..config import ConfigManager

# ------------------------
#  LAP
# ------------------------
LAP_DEFAULT_VALUE = 0.0

# ------------------------
# UI
# ------------------------
SCREEN_WIDTH = ConfigManager.get_config().width
SCREEN_HEIGHT = ConfigManager.get_config().height

BUTTON_HEIGHT = 72

LAP_WIDGET_OFFSET_Y = 12

FOOTER_BUTTONGROUP_MARGIN = 8
FOOTER_BUTTONGROUP_X = 10
FOOTER_BUTTONGROUP_Y = (
    SCREEN_HEIGHT
    - BUTTON_HEIGHT
    - (FOOTER_BUTTONGROUP_MARGIN + FOOTER_BUTTONGROUP_MARGIN)
)


HEADER_TITLE_TOPLEFT = (30, 30)
HEADER_LINE_TOPLEFT = (0, 90)

HEADER_BACKBUTTON_Y = 10
HEADER_BACKBUTTON_GAP = 12
HEADER_BACKBUTTON_SIZE = (74, 74)
HEADER_BACKBUTTON_POSITION = (
    SCREEN_WIDTH - HEADER_BACKBUTTON_SIZE[0] - HEADER_BACKBUTTON_GAP,
    HEADER_BACKBUTTON_Y,
)

# enter_ip_state
BUTTONS_PER_ROW = 3
BUTTON_DIMENSIONS = (114, 78)
BUTTON_MARGIN = 7
BUTTON_GRID_OFFSET = (
    BUTTON_DIMENSIONS[0] + BUTTON_MARGIN,
    BUTTON_DIMENSIONS[1] + BUTTON_MARGIN,
)
NUMPAD_OFFSET = (62, 228)

RECENT_CONNECTIONS_POSITION = (822, 180)

RECENT_BUTTONS_PER_ROW = 1
RECENT_BUTTONS_DIMENSIONS = (280, 74)
RECENT_BUTTONS_MARGIN = 12
RECENT_BUTTONS_GRID_OFFSET = (
    RECENT_BUTTONS_DIMENSIONS[0] + RECENT_BUTTONS_MARGIN,
    RECENT_BUTTONS_DIMENSIONS[1] + RECENT_BUTTONS_MARGIN,
)
RECENT_BUTTONS_OFFSET = (680, 210)
